### ISSUE TITLE
DCAT: Updates to ack section

### ISSUE THREAD

**Issue by andrea-perego** [w3c/dx-dcat#294]
To be added:
- WG members:
  - Linda van den Brink (see https://github.com/w3c/dx-dcat/issues/280)
- External feedback:
  - Ruth Duerr (see https://github.com/w3c/dx-dcat/issues/295)
  - Renato Iannella (see https://github.com/w3c/dx-dcat/issues/291)
  - Addison Phillips (see https://github.com/w3c/dx-dcat/issues/289, https://github.com/w3c/dx-dcat/issues/288, https://github.com/w3c/dx-dcat/issues/287)
  - Yves Coene (see https://github.com/w3c/dx-dcat/issues/286)
  - James Passmore (see https://github.com/w3c/dx-dcat/issues/285)
  - Siri Jodha S. Khalsa (see https://github.com/w3c/dx-dcat/issues/275#issuecomment-508655194)
  - Chris Wood (see https://github.com/w3c/dx-dcat/issues/269)

**Comment by andrea-perego** [comment]
Revisions implemented in PR https://github.com/w3c/dxwg/pull/1021

**Comment by riccardoAlbertoni** [comment]
Further updates of acknowledgment are tracked by issue w3c/dx-dcat#263 . So we can close this.

**Comment by davebrowning** [comment]
Agreed
