### ISSUE TITLE
dcat:distribution - check constraints

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/dx-dcat#443]
In DCAT v1 the property `dcat:distribution` is axiomatized 
```
dcat:distribution
  rdf:type owl:ObjectProperty ;
  rdfs:domain dcat:Dataset ;
  rdfs:range dcat:Distribution ;
.
```

1. Verify that the range is appropriate and necessary
2. Verify that the domain is appropriate and necessary (see w3c/dx-dcat#451)
3. Consider whether any guarded constraints (using owl:Restriction) should be introduced (see w3c/dx-dcat#454)

**Comment by makxdekkers** [comment]
I would vote to keep the domain and range here -- this property is one of the properties that are part of the backbone structure of DCAT:
Catalog > dataset > Dataset > distribution > Distribution

**Comment by dr-shorthair** [comment]
Do we need an inverse property here - to allow a distro to point to the dataset that it purports to instantiate?

**Comment by dr-shorthair** [comment]
In this case I think an inverse property makes sense. 
A Distro will usually know which Dataset that it is related to. 

Otherwise, Makx makes a compelling case for retaining domain and range.

**Comment by akuckartz** [comment]
No inverse properties please. They are not necessary. But that probably should better be discussed in a separate issue.

**Comment by dr-shorthair** [comment]
Discussion on inverse of dcat:distribution moved to w3c/dx-dcat#416

**Comment by dr-shorthair** [comment]
+1 to no change

**Comment by dr-shorthair** [comment]
https://www.w3.org/2018/03/21-dxwgdcat-minutes
resolved: no change to domain/range of dcat:distribution
